BACKUP DATABASE SoftUni TO DISK='D:\Programming\C#DB\MS SQL Server\01.EXERCISEDATA DEFINITION AND DATATYPES\softuni-backup.bak'

   DROP DATABASE SoftUni

RESTORE DATABASE SoftUni FROM DISK='D:\Programming\C#DB\MS SQL Server\01.EXERCISEDATA DEFINITION AND DATATYPES\softuni-backup.bak'
